
# Setup

title: Waterloo Region for Seniors
description: A resource for all seniors to get everything that they're looking for
remote_theme: pmarsceill/just-the-docs
#theme: jekyll-theme-hacker
# baseurl:'/seniorinfo'

author:
  name:     'Isaiah Thompson'
  url:      https://isaiahsdc.github.io
  
github:
  repo:     https://github.com/isaiahSDC/SeniorInfooooooooo

#logo: [Location of the logo]
#show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
